import React, { useEffect, useMemo, useState } from 'react'
import * as XLSX from 'xlsx'
import { supabase } from './supabase'

const empty = { articulo:'', cantidad:1, unidad:'PZA', precio:0, tienda:'', proveedor:'', fecha:new Date().toISOString().slice(0,10), area:'', empresa:'SIONLAB', facturado_con:'', facturado:false, compro:'', pago:'', estatus:'Pendiente', recurrente:false, frecuencia:'mensual', proximo_aviso:'' }
const fields = [['articulo','Artículo'],['cantidad','Cantidad'],['unidad','UM'],['precio','Precio'],['tienda','Tienda'],['proveedor','Proveedor'],['fecha','Fecha'],['area','Área'],['empresa','Empresa'],['facturado_con','Facturado con'],['compro','Compró'],['pago','Pago'],['estatus','Estatus'],['proximo_aviso','Fecha de aviso']]
const money = new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'})
const norm = v => String(v ?? '').trim()
const excelDate = value => {
  if (!value) return null
  if (value instanceof Date) return value.toISOString().slice(0,10)
  if (typeof value === 'number') { const d=XLSX.SSF.parse_date_code(value); return d?`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`:null }
  const d=new Date(value); return Number.isNaN(d.valueOf())?null:d.toISOString().slice(0,10)
}
const rowFromExcel = r => ({
  consecutivo: Number(r.CONS ?? r['CONS.'] ?? r.Consecutivo ?? 0) || null, articulo:norm(r.ARTICULO), cantidad:Number(r.CANTIDAD)||1, unidad:norm(r.UM), precio:Number(r.PRECIO ?? r['PRECIO '])||0, tienda:norm(r.TIENDA), fecha: excelDate(r.FECHA), area:norm(r.AREA), empresa:norm(r.EMPRESA), facturado_con:norm(r['FACTURADO CON']), facturado:['SI','SÍ',true,'TRUE'].includes(r.FACTURADO), compro:norm(r.COMPRO), pago:norm(r.PAGO), estatus:norm(r.ESTATUS)||'Pendiente'
})

export default function App(){
  const [items,setItems]=useState([]), [form,setForm]=useState(empty), [editing,setEditing]=useState(null), [search,setSearch]=useState(''), [loading,setLoading]=useState(true), [message,setMessage]=useState(''), [session,setSession]=useState(null), [credentials,setCredentials]=useState({email:'',password:''})
  const configured=!!supabase
  const load=async()=>{ if(!supabase){setLoading(false);return}; setLoading(true); const {data,error}=await supabase.from('compras').select('*').order('fecha',{ascending:false}); if(error)setMessage(error.message); else setItems(data||[]); setLoading(false) }
  useEffect(()=>{if(!supabase){setLoading(false);return};supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)load();else setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)load()});return()=>subscription.unsubscribe()},[])
  const login=async e=>{e.preventDefault();const {error}=await supabase.auth.signInWithPassword(credentials);if(error)setMessage(error.message)}
  const filtered=useMemo(()=>items.filter(x=>Object.values(x).join(' ').toLowerCase().includes(search.toLowerCase())),[items,search])
  const total=useMemo(()=>filtered.reduce((s,x)=>s+Number(x.precio||0),0),[filtered])
  const update=(k,v)=>{ if(k==='articulo'){ const last=[...items].find(x=>x.articulo?.toLowerCase()===String(v).toLowerCase()); if(last)return setForm(f=>({...f,...last,id:undefined,articulo:v,fecha:new Date().toISOString().slice(0,10),proximo_aviso:''})) } setForm(f=>({...f,[k]:v})) }
  const save=async e=>{e.preventDefault(); if(!supabase)return setMessage('Configura .env con los datos de Supabase.'); const payload={...form,cantidad:Number(form.cantidad),precio:Number(form.precio),facturado:!!form.facturado,creado_por:session?.user?.id}; delete payload.id; const wasEditing=!!editing; const q=wasEditing?supabase.from('compras').update(payload).eq('id',editing):supabase.from('compras').insert(payload).select().single(); const {data,error}=await q; if(error)return setMessage(error.message); if(!wasEditing){const {error:alertError}=await supabase.functions.invoke('enviar-notificacion',{body:{compra:data}}); if(alertError)console.warn('No se pudo enviar el aviso externo:',alertError.message)} if('Notification'in window&&Notification.permission==='granted')new Notification('Nueva compra registrada',{body:`${payload.articulo} · ${money.format(payload.precio)}`,icon:'/icon.svg'}); setForm(empty);setEditing(null);setMessage(wasEditing?'Compra actualizada.':'Compra guardada y alertas solicitadas.');load()}
  const edit=x=>{setEditing(x.id);setForm({...empty,...x,fecha:x.fecha?.slice(0,10)||''});window.scrollTo({top:0,behavior:'smooth'})}
  const remove=async id=>{if(!confirm('¿Eliminar esta compra?'))return; const {error}=await supabase.from('compras').delete().eq('id',id); if(error)setMessage(error.message);else load()}
  const importExcel=async e=>{const file=e.target.files[0];if(!file||!supabase)return; const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const sheet=wb.Sheets[wb.SheetNames[0]];const grid=XLSX.utils.sheet_to_json(sheet,{header:1,defval:''});const headerRow=grid.findIndex(row=>norm(row[0]).startsWith('CONS')&&norm(row[1])==='ARTICULO');if(headerRow<0){setMessage('No encontré los encabezados CONS. y ARTICULO en el Excel.');return}const headers=grid[headerRow].map(norm);const rows=grid.slice(headerRow+1).map(row=>Object.fromEntries(headers.map((header,index)=>[header,row[index]]))).filter(row=>norm(row.ARTICULO));const purchases=rows.map(rowFromExcel);const {error}=await supabase.from('compras').insert(purchases); setMessage(error?error.message:`Se importaron ${purchases.length} compras.`);if(!error)load();e.target.value=''}
  if(configured&&!session)return <main className="login"><section className="panel"><span className="eyebrow">SIONLAB</span><h1>Control de Compras</h1><p>Inicia sesión para consultar y administrar las compras.</p>{message&&<div className="message">{message}</div>}<form onSubmit={login} className="form one"><label>Correo<input type="email" required value={credentials.email} onChange={e=>setCredentials(c=>({...c,email:e.target.value}))}/></label><label>Contraseña<input type="password" required value={credentials.password} onChange={e=>setCredentials(c=>({...c,password:e.target.value}))}/></label><button className="primary">Entrar</button></form></section></main>
  return <main><header><div><span className="eyebrow">SIONLAB</span><h1>Control de Compras</h1><p>Gastos generales de operación</p></div><div><button onClick={async()=>{if('Notification'in window){const p=await Notification.requestPermission();setMessage(p==='granted'?'Avisos web activados.':'Activa las notificaciones en el navegador.')}}}>Activar avisos</button><div className={configured?'badge ok':'badge'}>{configured?'Conectado a Supabase':'Falta configuración'}</div>{configured&&<button onClick={()=>supabase.auth.signOut()}>Salir</button>}</div></header>
  {!configured&&<section className="notice">Abre <code>.env.example</code>, crea <code>.env</code> y pega la URL y Publishable Key de tu nuevo proyecto.</section>}
  {message&&<div className="message">{message}<button onClick={()=>setMessage('')}>×</button></div>}
  <section className="cards"><article><small>Compras mostradas</small><strong>{filtered.length}</strong></article><article><small>Total</small><strong>{money.format(total)}</strong></article><article><small>Áreas</small><strong>{new Set(filtered.map(x=>x.area).filter(Boolean)).size}</strong></article></section>
  <section className="panel"><h2>{editing?'Editar compra':'Captura inteligente de gasto'}</h2><p>Escribe un artículo ya usado y se completarán automáticamente sus últimos datos.</p><datalist id="articulos">{[...new Set(items.map(x=>x.articulo).filter(Boolean))].map(x=><option key={x} value={x}/>)}</datalist><form onSubmit={save} className="form">{fields.map(([key,label])=><label key={key}>{label}<input required={key==='articulo'} list={key==='articulo'?'articulos':undefined} type={key==='cantidad'||key==='precio'?'number':key==='fecha'||key==='proximo_aviso'?'date':'text'} min={key==='cantidad'?'1':key==='precio'?'0':undefined} step={key==='precio'?'0.01':undefined} value={form[key]??''} onChange={e=>update(key,e.target.value)}/></label>)}<label className="check"><input type="checkbox" checked={form.facturado} onChange={e=>update('facturado',e.target.checked)}/> Facturado</label><label className="check"><input type="checkbox" checked={form.recurrente} onChange={e=>update('recurrente',e.target.checked)}/> Gasto recurrente</label>{form.recurrente&&<label>Frecuencia<select value={form.frecuencia} onChange={e=>update('frecuencia',e.target.value)}><option value="semanal">Semanal</option><option value="quincenal">Quincenal</option><option value="mensual">Mensual</option></select></label>}<div className="actions"><button className="primary">{editing?'Guardar cambios':'Guardar gasto y avisar'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty)}}>Cancelar</button>}</div></form></section>
  <section className="panel"><div className="toolbar"><div><h2>Historial de compras</h2><input placeholder="Buscar artículo, tienda, área..." value={search} onChange={e=>setSearch(e.target.value)}/></div><label className="import">Importar Excel<input type="file" accept=".xlsx,.xls" onChange={importExcel}/></label></div><div className="tablewrap"><table><thead><tr><th>Fecha</th><th>Artículo</th><th>Área</th><th>Tienda</th><th>Pago</th><th>Total</th><th>Estatus</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan="8">Cargando...</td></tr>:filtered.map(x=><tr key={x.id}><td>{x.fecha?.slice(0,10)}</td><td><b>{x.articulo}</b><br/><small>{x.cantidad} {x.unidad}</small></td><td>{x.area}</td><td>{x.tienda}</td><td>{x.pago}</td><td>{money.format(x.precio||0)}</td><td><span className="status">{x.estatus}</span></td><td><button onClick={()=>edit(x)}>Editar</button><button className="danger" onClick={()=>remove(x.id)}>Eliminar</button></td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan="8">No hay compras todavía.</td></tr>}</tbody></table></div></section></main>
}
