import React,{useEffect,useMemo,useState} from 'react'
import * as XLSX from 'xlsx'
import {supabase} from './supabase'
import './admin.css'

const blank={articulo:'',cantidad:1,unidad:'PZA',precio:0,tienda:'',proveedor:'',fecha:new Date().toISOString().slice(0,10),area:'',empresa:'SIONLAB',facturado_con:'',facturado:false,compro:'',pago:'',estatus:'Pendiente'}
const textFields=[['articulo','Artículo'],['unidad','Unidad'],['tienda','Tienda'],['proveedor','Proveedor'],['area','Área'],['empresa','Empresa'],['facturado_con','Facturado con'],['compro','Compró'],['pago','Pago'],['estatus','Estatus']]
const perms=[['ver','Ver compras'],['crear','Capturar'],['editar','Modificar'],['eliminar','Eliminar'],['importar','Importar Excel'],['configurar','Configuración']]
const norm=v=>String(v??'').trim()
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'})
const has=(profile,p)=>profile?.es_admin||profile?.permisos?.includes(p)

export default function App(){
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[items,setItems]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[tab,setTab]=useState('compras'),[search,setSearch]=useState(''),[message,setMessage]=useState(''),[login,setLogin]=useState({email:'',password:''}),[users,setUsers]=useState([]),[recipients,setRecipients]=useState([]),[invite,setInvite]=useState({email:'',rol:'Capturista',permisos:['ver','crear']}),[newRecipient,setNewRecipient]=useState({canal:'email',destinatario:''}),[password,setPassword]=useState('')
 const load=async s=>{const uid=(s||session)?.user?.id;if(!uid)return;const [{data:p},{data:c}]=await Promise.all([supabase.from('perfiles').select('*').eq('id',uid).single(),supabase.from('compras').select('*').order('fecha',{ascending:false})]);setProfile(p);setItems(c||[]);if(p?.es_admin){const [{data:u},{data:r}]=await Promise.all([supabase.from('perfiles').select('*').order('creado_en'),supabase.from('destinatarios_alerta').select('*').order('creado_en')]);setUsers(u||[]);setRecipients(r||[])}}
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)load(data.session)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)load(s)});return()=>subscription.unsubscribe()},[])
 const suggestions=useMemo(()=>Object.fromEntries(textFields.map(([k])=>[k,[...new Set(items.map(x=>norm(x[k])).filter(Boolean))].sort((a,b)=>a.localeCompare(b))])),[items])
 const filtered=useMemo(()=>items.filter(x=>Object.values(x).join(' ').toLowerCase().includes(search.toLowerCase())),[items,search])
 const authenticate=async e=>{e.preventDefault();const {error}=await supabase.auth.signInWithPassword(login);setMessage(error?.message||'')}
 const chooseArticle=value=>{setForm(f=>({...f,articulo:value}));const prior=items.find(x=>norm(x.articulo).toLowerCase()===norm(value).toLowerCase());if(prior&&confirm('Este gasto ya existe. ¿Deseas copiar sus datos para una compra nueva?'))copy(prior)}
 const copy=x=>{const next={...blank,...Object.fromEntries(Object.keys(blank).map(k=>[k,x[k]??blank[k]])),fecha:new Date().toISOString().slice(0,10)};setEditing(null);setForm(next);setTab('compras');scrollTo({top:0,behavior:'smooth'})}
 const save=async e=>{e.preventDefault();const payload={...form,cantidad:Number(form.cantidad),precio:Number(form.precio),creado_por:session.user.id};const query=editing?supabase.from('compras').update(payload).eq('id',editing):supabase.from('compras').insert(payload);const {error}=await query;if(error)return setMessage(error.message);if(!editing)supabase.functions.invoke('enviar-notificacion',{body:{compra:payload}});setForm(blank);setEditing(null);setMessage('Compra guardada.');load()}
 const edit=x=>{setForm(Object.fromEntries(Object.keys(blank).map(k=>[k,x[k]??blank[k]])));setEditing(x.id);scrollTo({top:0,behavior:'smooth'})}
 const remove=async id=>{if(!confirm('¿Eliminar definitivamente esta compra?'))return;const {error}=await supabase.from('compras').delete().eq('id',id);setMessage(error?.message||'Compra eliminada.');load()}
 const importExcel=async e=>{const wb=XLSX.read(await e.target.files[0].arrayBuffer(),{cellDates:true});const grid=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:''});const h=grid.findIndex(r=>norm(r[0]).startsWith('CONS')&&norm(r[1])==='ARTICULO');if(h<0)return setMessage('No encontré los encabezados del Excel.');const keys=grid[h].map(norm);const rows=grid.slice(h+1).map(r=>Object.fromEntries(keys.map((k,i)=>[k,r[i]]))).filter(r=>r.ARTICULO).map(r=>({consecutivo:Number(r['CONS.'])||null,articulo:norm(r.ARTICULO),cantidad:Number(r.CANTIDAD)||1,unidad:norm(r.UM),precio:Number(r['PRECIO '])||0,tienda:norm(r.TIENDA),fecha:new Date(r.FECHA).toISOString().slice(0,10),area:norm(r.AREA),empresa:norm(r.EMPRESA),facturado_con:norm(r['FACTURADO CON']),facturado:['SI','SÍ',true].includes(r.FACTURADO),compro:norm(r.COMPRO),pago:norm(r.PAGO),estatus:norm(r.ESTATUS)||'Pendiente',creado_por:session.user.id}));const {error}=await supabase.from('compras').insert(rows);setMessage(error?.message||`Se importaron ${rows.length} compras.`);load()}
 const inviteUser=async e=>{e.preventDefault();const {error}=await supabase.functions.invoke('administrar-usuarios',{body:{accion:'invitar',...invite}});setMessage(error?.message||'Invitación enviada.');if(!error)setInvite({email:'',rol:'Capturista',permisos:['ver','crear']})}
 const updateUser=async u=>{const {error}=await supabase.from('perfiles').update({rol:u.rol,permisos:u.permisos}).eq('id',u.id);setMessage(error?.message||'Permisos actualizados.');load()}
 const addRecipient=async e=>{e.preventDefault();const {error}=await supabase.from('destinatarios_alerta').insert(newRecipient);setMessage(error?.message||'Destinatario agregado.');if(!error)setNewRecipient({canal:'email',destinatario:''});load()}
 const changePassword=async e=>{e.preventDefault();const {error}=await supabase.auth.updateUser({password});setMessage(error?.message||'Contraseña actualizada.');if(!error)setPassword('')}
 if(!session)return <main className="login"><section className="panel"><h1>Control de Compras</h1><p>Acceso únicamente por invitación.</p><form onSubmit={authenticate} className="form one"><label>Correo<input type="email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} required/></label><label>Contraseña<input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} required/></label><button className="primary">Entrar</button></form>{message&&<p className="message">{message}</p>}</section></main>
 return <main><header><div><b>SIONLAB</b><h1>Control de Compras</h1><small>{profile?.rol}</small></div><nav><button onClick={()=>setTab('compras')}>Compras</button><button onClick={()=>setTab('cuenta')}>Mi contraseña</button>{has(profile,'configurar')&&<button onClick={()=>setTab('config')}>Configuración</button>}<button onClick={()=>supabase.auth.signOut()}>Salir</button></nav></header>{message&&<div className="message">{message}<button onClick={()=>setMessage('')}>×</button></div>}
 {tab==='compras'&&<><section className="cards"><article><small>Compras</small><strong>{filtered.length}</strong></article><article><small>Total</small><strong>{money.format(filtered.reduce((a,x)=>a+Number(x.precio||0),0))}</strong></article></section>{has(profile,editing?'editar':'crear')&&<section className="panel"><h2>{editing?'Editar compra':'Nueva compra inteligente'}</h2>{Object.entries(suggestions).map(([k,v])=><datalist id={`list-${k}`} key={k}>{v.map(x=><option value={x} key={x}/>)}</datalist>)}<form className="form" onSubmit={save}>{textFields.map(([k,l])=><label key={k}>{l}<input list={`list-${k}`} value={form[k]} onChange={e=>k==='articulo'?chooseArticle(e.target.value):setForm({...form,[k]:e.target.value})} required={k==='articulo'}/></label>)}<label>Cantidad<input type="number" min="1" value={form.cantidad} onChange={e=>setForm({...form,cantidad:e.target.value})}/></label><label>Precio<input type="number" min="0" step=".01" value={form.precio} onChange={e=>setForm({...form,precio:e.target.value})}/></label><label>Fecha<input type="date" value={form.fecha} onChange={e=>setForm({...form,fecha:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.facturado} onChange={e=>setForm({...form,facturado:e.target.checked})}/>Facturado</label><div className="actions"><button className="primary">Guardar</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(blank)}}>Cancelar</button>}</div></form></section>}<section className="panel"><div className="toolbar"><input placeholder="Buscar..." value={search} onChange={e=>setSearch(e.target.value)}/>{has(profile,'importar')&&<label className="import">Importar Excel<input type="file" accept=".xlsx,.xls" onChange={importExcel}/></label>}</div><div className="tablewrap"><table><thead><tr><th>Fecha</th><th>Artículo</th><th>Tienda</th><th>Área</th><th>Total</th><th>Acciones</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td>{x.fecha}</td><td>{x.articulo}</td><td>{x.tienda}</td><td>{x.area}</td><td>{money.format(x.precio)}</td><td>{has(profile,'crear')&&<button onClick={()=>copy(x)}>Copiar</button>}{has(profile,'editar')&&<button onClick={()=>edit(x)}>Editar</button>}{has(profile,'eliminar')&&<button className="danger" onClick={()=>remove(x.id)}>Eliminar</button>}</td></tr>)}</tbody></table></div></section></>}
 {tab==='cuenta'&&<section className="panel"><h2>Cambiar mi contraseña</h2><form className="form one" onSubmit={changePassword}><label>Nueva contraseña<input type="password" minLength="8" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary">Cambiar contraseña</button></form></section>}
 {tab==='config'&&has(profile,'configurar')&&<><section className="panel"><h2>Invitar usuario</h2><form className="form" onSubmit={inviteUser}><label>Correo<input type="email" value={invite.email} onChange={e=>setInvite({...invite,email:e.target.value})} required/></label><label>Nombre del rol<input value={invite.rol} onChange={e=>setInvite({...invite,rol:e.target.value})}/></label><div className="permissions">{perms.map(([p,l])=><label className="check" key={p}><input type="checkbox" checked={invite.permisos.includes(p)} onChange={e=>setInvite({...invite,permisos:e.target.checked?[...invite.permisos,p]:invite.permisos.filter(x=>x!==p)})}/>{l}</label>)}</div><button className="primary">Enviar invitación</button></form></section><section className="panel"><h2>Usuarios y privilegios</h2>{users.map((u,i)=><div className="userrow" key={u.id}><b>{u.email}</b><input value={u.rol} onChange={e=>setUsers(users.map((x,j)=>j===i?{...x,rol:e.target.value}:x))}/>{perms.map(([p,l])=><label className="check" key={p}><input type="checkbox" checked={u.es_admin||u.permisos?.includes(p)} disabled={u.es_admin} onChange={e=>setUsers(users.map((x,j)=>j===i?{...x,permisos:e.target.checked?[...(x.permisos||[]),p]:(x.permisos||[]).filter(y=>y!==p)}:x))}/>{l}</label>)}{!u.es_admin&&<button onClick={()=>updateUser(u)}>Guardar</button>}</div>)}</section><section className="panel"><h2>Destinatarios de alertas</h2><form className="form" onSubmit={addRecipient}><select value={newRecipient.canal} onChange={e=>setNewRecipient({...newRecipient,canal:e.target.value})}><option value="email">Correo</option><option value="whatsapp">WhatsApp</option></select><input placeholder="Correo o número con +52" value={newRecipient.destinatario} onChange={e=>setNewRecipient({...newRecipient,destinatario:e.target.value})} required/><button className="primary">Agregar</button></form>{recipients.map(r=><div className="userrow" key={r.id}><span>{r.canal}: {r.destinatario}</span><button className="danger" onClick={async()=>{await supabase.from('destinatarios_alerta').delete().eq('id',r.id);load()}}>Eliminar</button></div>)}</section></>}
 </main>
}
